name: Build triton-util

on:
  push:
    branches: [main]
    paths:
      - triton_util/**
      - .github/workflows/build.yml
  pull_request:
    paths:
      - triton_util/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Upgrade pip and install tools
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel

      - name: Build the package
        run: |
          cd triton_util
          python -m build

      - name: Install the package
        run: |
          pip install ./triton_util[dev]
