name: tcv-image

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - .github/workflows/image-tcv.yml
      - tcv/**
  pull_request:
    paths:
      - .github/workflows/image-tcv.yml
      - tcv/**
  workflow_dispatch:

jobs:
  tcv-image-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - IMAGE_NAME: tcv
            IMAGE_FILE: tcv/images/amd64.dockerfile
            PLATFORMS: linux/amd64
            LABEL: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # NOTE:  setting fetch-depth to 0 to retrieve the entire history
          # instead of a shallow-clone so that all tags are fetched as well.
          # This is necessary for computing the VERSION using `git describe`
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v8.1.5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up cosign
        uses: sigstore/cosign-installer@main

      - name: Login to Quay
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: docker/login-action@v3
        with:
          registry: quay.io/tkm/tcv
          username: ${{ secrets.qt_username }}
          password: ${{ secrets.qt_password }}

      - name: Build and (conditionally) push image
        id: build-push-image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.PLATFORMS }}
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: quay.io/tkm/${{ matrix.IMAGE_NAME }}:${{ matrix.LABEL }}
          file: ${{ matrix.IMAGE_FILE }}

      - name: Sign images with GitHub OIDC Token
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: |
          cosign sign -y quay.io/tkm/${{ matrix.IMAGE_NAME }}:${{ matrix.LABEL }}@${{ steps.build-push-image.outputs.digest }}

      - name: Generate image attestation
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

        uses: actions/attest-build-provenance@v2
        with:
          subject-name: quay.io/tkm/${{ matrix.IMAGE_NAME }}
          subject-digest: ${{ steps.build-push-image.outputs.digest }}
          push-to-registry: true
  tcv-image-sbom:
    needs: tcv-image-build
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/sbom-tcv.yml
    with:
      image-name: ${{ matrix.IMAGE_NAME }}
      image-tag: ${{ matrix.LABEL }}
    secrets:
      qt_username: ${{ secrets.qt_username }}
      qt_password: ${{ secrets.qt_password }}
