name: MCM Build & Attach Artifacts

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - mcm-v*

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build wheel and sdist
        run: |
          python -m pip install --upgrade build
          python -m build
          ls -l dist/

      - name: Publish GitHub Release and upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            mcm/dist/*.whl
            mcm/dist/*.tar.gz
