name: MCV Build

on: # yamllint disable-line rule:truthy
  push:
    paths:
      - mcv/**
  pull_request:
    paths:
      - mcv/**

jobs:
  build:
    name: Make build (mcv)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.0

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgpgme-dev \
            libbtrfs-dev

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest

      - name: Prepare vendored dependencies
        working-directory: mcv
        run: |
          go mod tidy
          go mod vendor

      - name: Run golangci-lint
        working-directory: mcv
        run: |
          golangci-lint run --timeout=5m --modules-download-mode=vendor ./...

      - name: Build with Makefile
        run: make mcv

      - name: Run unit tests
        run: make mcv-test
